name: i18n:pull JS translations
on: workflow_dispatch # manually trigger

jobs:
  translations:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install & Build
      run: |
        npm install
  
    - name: install transifex-client
      run: |
        pip install transifex-client

      # store token
    - name: store token
      run: |
        tx init --token ${{ secrets.TRANSIFEX_TOKEN }} --force --no-interactive

    # pull all lang
    - name: pull translations
      run: |
        tx pull -a -f

    # compile .po file to json
    - name: compile
      run: |
        npm run compile_catalog

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: i18n:pull translations
        title: i18n:pull translations
        body: i18n:pull translations
        branch: 101-translations  # name of branch which PR is created from
        delete-branch: true  # delete branch once merged,closed
