name: i18n:extract,push,pull JS translations
on:
  push:
    branches:
      - master

jobs:
  translations:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install & dep
      run: |
        npm install
  
      - name: install transifex-client
        run: |
          pip install transifex-client

      # store token
      - name: store token
        run: |
          tx init --token ${{ secrets.TRANS_TOKEN }} --force --no-interactive

      # extract
      - name: extract_messages
        run: |
          npm run extract_messages
  
      # push
      - name: push_messages
        run: |
          tx push -s -t
  
      # pull all lang
      - name: pull translations
        run: |
          tx pull -a

      # compile .po file to json
      - name: compile
        run: |
          npm run compile_catalog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: i18n:extract,push,pull translations
          title: i18n:extract,push,pull translations
          body: i18n:extract,push,pull translations
          branch: 101-translations  # name of branch which PR is created from
          delete-branch: true  # delete branch once merged,closed